<?php
if (Mage::helper('megamenu')->isMegamenuModuleEnabled()):
    $menus = $this->getMenus();
    $backgroundColor = Mage::registry('backgroundColor');
    $fontSize = Mage::registry('fontSize');
    $fontFamily = Mage::registry('fontFamily');
    $fontColor = Mage::registry('fontColor') . $fontSize . $fontFamily;
    ?>
    <div class="megamenu nav-container" >
        <ul id="nav" style="<?php echo $backgroundColor . $fontColor ?>">
            <?php
            foreach ($menus as $menu) {
                ?>
                <li>
                    <?php if ($menu['type_id'] == 5): ?> 
                        <a id="anchor_menu_type_<?php echo $menu['entity_id']; ?>" 
                           class="megamenu-lable" href="" style="<?php echo $fontColor; ?>"
                           title="<?php echo $menu['titel'];?>" 
                           >
                            <?php echo $menu['name']; ?>
                        </a>
                    <?php else: ?>
                        <a class="megamenu-lable" href="javascript:void(0)" href="" 
                           style="<?php echo $fontColor; ?>" 
                           title="<?php echo $menu['titel'];?>" >
                            <?php echo $menu['name']; ?>
                        </a>                
                    <?php endif; ?>
                    <div class="magestore-megamenu" style="<?php echo $backgroundColor . $fontColor ?>">
                        <?php echo $template = $this->generateMenu($menu['entity_id'], $menu['template_id']); ?> 
                    </div>

                </li>
                <?php
            }
            ?>
        </ul>
    </div>
<?php endif; ?>
<script>

$j('body').on('click','.megamenu-lable',function(){
    $j('.magestore-megamenu').slideUp();
    $j(this).next('.magestore-megamenu').show();
})
</script>
<?php //die(); ?>
