<?php
$data = $this->getTemplateData();
$backgroundColor = Mage::registry('backgroundColor');
$fontSize = Mage::registry('fontSize');
$fontFamily = Mage::registry('fontFamily');
$fontColor = Mage::registry('fontColor') . $fontSize . $fontFamily;
?>
<div class="block-megamenu sub-menu" id="menu1" style="<?php echo $backgroundColor . $fontColor ?>">
    <h1 class="megamenu-title">Contact Form</h1>
    <ul class="block-contact">
        <li class="level1-megamenu"> 
            <div class="megamenu-header">
                <?php $block = Mage::getModel('cms/block')->load($data['header']); ?>
                <?php echo $block->getContent(); ?>
            </div>
            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('contacts/form.phtml')->toHtml(); ?>            
            <div   class="footer-megamenu"> 
                <span>
                    <?php $footerblock = Mage::getModel('cms/block')->load($data['footer']); ?>
                    <?php echo $footerblock->getContent(); ?>
                </span> 
            </div>
        </li>
    </ul>
</div>